version: '3.8'

services:

  app:
    image: juanfdojaramillo/pruebadevco:latest
    container_name: app
    restart: always
    ports:
      - 8000:8000

    volumes:
      - ./app:/app

    networks:
      - backend

networks:
  backend:
    driver: bridge