name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip
          pip3 install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests

      - name: Analyze code with SonarCloud
        uses: sonarsource/sonarcloud-github-actio@main
        with:
          projectKey: JuanFdoJaramillo_PruebaDevco_
          organization: juanfdojaramillo
          token: ${5c79c4d2a20f222221d1a606f010a7274a5d1043}

      - name: Build Docker image
        run: |
          docker build -t juanfdojaramillo/pruebadevco:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push juanfdojaramillo/pruebadevco:latest
